services:
  # PostgreSQL Database
  - type: pserv
    name: link-bus-db
    env: docker
    plan: free
    databases:
      - name: link_bus_db
        user: link_bus_user

  # Web Service (API + Frontend)
  - type: web
    name: link-bus-system
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: link-bus-db
          property: connectionString
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: SESSION_SECRET
        generateValue: true
    healthCheckPath: /api/health 